### ISSUE TITLE
Ability to provide a url and auto-download the theme from there

### ISSUE THREAD

**Issue by FichteFoll** [Colorsublime/Colorsublime-Themes#166]
Since most color scheme authors host their tmTheme files at a different place, it seems like a good idea to allow specification of a url where the theme is downloaded from automatically.

https://github.com/aziz/tmTheme-Editor does this.

Also, I don't know if the ST plugin auto-updates themes (since they can already be updated) but that would be a nice feature as well, imo. I haven't actually used it though.

**Comment by blopker** [comment]
I'm not sure about specifying the URL, that seems like a larger discussion. I wouldn't want the client to download content from arbitrary servers (!!!), if that's what you were thinking. 

However, the auto-updating is an interesting idea. Currently the plugin does update the theme list, but would only update the current theme if the user reselects it. My main concern would be pulling a user's theme from under their feet if the author makes a change they don't like.

**Comment by FichteFoll** [comment]
I was actually thinking of downloading the files on the colorsublime server and then providing the themes there for download. If you are concerned about arbitrary servers you could restrict it to github urls (which seems to be rather dominant, see https://github.com/aziz/tmTheme-Editor/blob/master/public/gallery.json).

**Comment by blopker** [comment]
So the URL feature is a no-go for now. We don't actually have a server to do it with. Aside from the server we host the website with everything is done off Github. Creating the infrastructure for this feature is prohibitively expensive time-wise. 

Although I like the auto update feature. Since that is plugin related I'll close the discussion here and move that feature to the plugin roadmap.

Thank you for your input.
Cheers! :beers:
