### ISSUE TITLE
Scheme vs. Theme

### ISSUE THREAD

**Issue by blopker** [Colorsublime/Colorsublime-Themes#33]
Not sure if this has been discussed, but schemes and themes are different in Sublime Text. What is in this repo are schemes. See https://github.com/buymeasoda/soda-theme/ for a theme.

Not sure it really matters though. Awesome site, btw!

**Comment by blopker** [comment]
We have another confused soul over in the plugin repo: https://github.com/Colorsublime/Colorsublime-Plugin/issues/17

We should consider changing theme to scheme as this thing gets more popular.

**Comment by smeijer** [comment]
I would say, don't change the name but extend the functionality instead.

Great plugin, would be awesome if we could change themes as well as schemes.

**Comment by blopker** [comment]
> if we could change themes

If only. The current ST API wouldn't allow for the same kind of functionality for actual themes. Themes (in the the ST sense) are much more heavy weight, in terms of number and size of files.

**Comment by GianlucaGuarini** [comment]
Guys colorsublime it's a free project It was made for fun in a couple of weekends. We will not spend any extra time enhancing it (adding themes, filters. likes...) because it requires too many changes on the backend/frontend and logic. We will still maintain it and fix the bugs but please accept it in the way it is.
